# this is a work flow on push and merge

name: xmpl CI/CD

on:                         # run this workflow on the following events
   [workflow_dispatch] 
      
   # paths:
   #   - 'src/**'

 
jobs:

  unit-test:
       runs-on: ubuntu-latest

       strategy:
            fail-fast: false
            matrix:
              node-version: [18.x, 20.x]  # Test on Node.js 18 and 20

       steps:

          - name: Checkout code   
            uses: actions/checkout@v4     # Download repo files into runner

          - name: Setup Node.js
            uses: actions/setup-node@v3 # Ready action to install Node.js
            with:
                node-version: ${{ matrix.node-version }} # Use version from matrix

          - name: Install dependencies
            run: npm install            # Install npm packages from package.json

          - name: Run tests
            run:  npm test -- --json --outputFile=test-results.json     # Run your unit tests (e.g., Jest)


          
          - name: Prepare artifact folder
            run: |
              mkdir -p test-artifact
              cp -r coverage test-artifact/coverage
              cp test-results.json test-artifact/

          - name: Upload test results
            uses: actions/upload-artifact@v4
            with:
              name: test-results-${{ matrix.node-version }}
              path: test-artifact
              retention-days: 5


  ########################## New Job to analyze using CodeQL ##########################   
     
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    permissions:                 # minimal permissions the job needs
      actions: read              # allow reading actions metadata
      contents: read             # allow reading repo contents
      security-events: write     # allow writing security/code-scanning events


    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]       # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}    


    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    # Analayzing the code 
    -  name: Perform CodeQL Analysis
       uses: github/codeql-action/analyze@v3  # run the actual security/quality scan

